import {
  HomeIcon,
  FunnelIcon,
  UsersIcon,
  LayersIcon,
  IdCardIcon,
  BuildingIcon,
  CalendarIcon,
  SoupIcon,
  NewspaperIcon,
  WalletIcon,
  InboxIcon,
  CheckCircleIcon,
  ClipboardIcon,
  ScanIcon,
  TriangleAlertIcon,
  SettingsIcon,
  BellIcon,
  SearchIcon,
  PlusIcon,
  XIcon,
  ChevronDownIcon,
  ChevronRightIcon,
  ChevronLeftIcon,
  EllipsisIcon,
  PencilIcon,
  Trash2Icon,
  FilterIcon,
  PhoneIcon,
  MailIcon,
  UploadIcon,
  DownloadIcon,
  QrCodeIcon,
  CameraIcon,
  PieChartIcon,
  RefreshCwIcon,
  CreditCardIcon,
  GiftIcon,
  TagIcon,
  ReceiptIcon,
  ClockIcon,
  ClockAlertIcon,
  ArrowUpIcon,
  ArrowDownIcon,
  ArrowRightIcon,
  ArrowLeftIcon,
  InfoIcon,
  CheckIcon,
  StarIcon,
  SparklesIcon,
  GripVerticalIcon,
  LogOutIcon,
  MenuIcon,
  EyeIcon,
  PauseIcon,
  PlayIcon,
  LockIcon,
  GlobeIcon,
  HeartIcon,
  StethoscopeIcon,
  SmileIcon,
  type LucideIcon,
} from 'lucide-react';

export const iconRegistry = {
  // nav
  Home: HomeIcon,
  Funnel: FunnelIcon,
  Users: UsersIcon,
  Layers: LayersIcon,
  IdCard: IdCardIcon,
  Building: BuildingIcon,
  Calendar: CalendarIcon,
  // ds.jsx Bowl (soup bowl / meal icon) — BowlIcon absent in lucide ^1.16; SoupIcon is the closest available bowl-shaped food icon
  Bowl: SoupIcon,
  News: NewspaperIcon,
  Wallet: WalletIcon,
  Inbox: InboxIcon,
  CheckCircle: CheckCircleIcon,
  Clipboard: ClipboardIcon,
  Scan: ScanIcon,
  // ds.jsx AlertTri → TriangleAlertIcon (lucide renamed AlertTriangle → TriangleAlert)
  AlertTri: TriangleAlertIcon,
  Settings: SettingsIcon,
  Bell: BellIcon,
  // util
  Search: SearchIcon,
  Plus: PlusIcon,
  X: XIcon,
  ChevronDown: ChevronDownIcon,
  ChevronRight: ChevronRightIcon,
  ChevronLeft: ChevronLeftIcon,
  // ds.jsx More (three dots horizontal) → EllipsisIcon
  More: EllipsisIcon,
  // ds.jsx Edit (pencil path) → PencilIcon
  Edit: PencilIcon,
  // ds.jsx Trash → Trash2Icon (standard trash with lines, closer match to ds path)
  Trash: Trash2Icon,
  Filter: FilterIcon,
  Phone: PhoneIcon,
  Mail: MailIcon,
  Upload: UploadIcon,
  Download: DownloadIcon,
  // ds.jsx QR → QrCodeIcon
  QR: QrCodeIcon,
  Camera: CameraIcon,
  PieChart: PieChartIcon,
  // ds.jsx Refresh (circular arrow) → RefreshCwIcon
  Refresh: RefreshCwIcon,
  CreditCard: CreditCardIcon,
  Gift: GiftIcon,
  Tag: TagIcon,
  Receipt: ReceiptIcon,
  Clock: ClockIcon,
  // ds.jsx ClockAlert (clock with alert dot) → ClockAlertIcon
  ClockAlert: ClockAlertIcon,
  ArrowUp: ArrowUpIcon,
  ArrowDown: ArrowDownIcon,
  ArrowRight: ArrowRightIcon,
  ArrowLeft: ArrowLeftIcon,
  Info: InfoIcon,
  Check: CheckIcon,
  Star: StarIcon,
  Sparkles: SparklesIcon,
  // ds.jsx GripDots (6-dot drag handle) → GripVerticalIcon (closest drag-handle in lucide)
  GripDots: GripVerticalIcon,
  // ds.jsx Logout → LogOutIcon
  Logout: LogOutIcon,
  Menu: MenuIcon,
  Eye: EyeIcon,
  Pause: PauseIcon,
  Play: PlayIcon,
  Lock: LockIcon,
  Globe: GlobeIcon,
  Heart: HeartIcon,
  Stethoscope: StethoscopeIcon,
  Smile: SmileIcon,
} as const satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof iconRegistry;
